version: '3'
volumes:
  vendor:
services:
  app:
    build: .
    command: sh -c "yarn --force && yarn run serve"
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "8000:8080"
 